platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

def shared_pods
  pod 'RxAlamoRecord', :path => '../'
end

target 'RxAlamoRecord_Example' do
  shared_pods
  pod 'SnapKit'
  pod 'NotificationBannerSwift'
  pod 'KeyboardSpy'
end

target 'RxAlamoRecordTests' do
  shared_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    
    if ['KeyboardSpy'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.0'
      end
    end
    
  end
end
