use_frameworks!

def shared_pods
  pod 'RxAlamoRecord', :path => '../'
end

target 'RxAlamoRecord_Example' do
  shared_pods
  pod 'SnapKit'
  pod 'NotificationBannerSwift'
  pod 'KeyboardSpy'
end

target 'RxAlamoRecordTests' do
  shared_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    swift42_projects = [
    'Kingfisher',
    'NotificationBannerSwift',
    'SnapKit',
    'MarqueeLabel',
    'Alamofire',
    'RxAlamoRecord',
    'AlamoRecord']
    
    if swift42_projects.include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    else
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.0'
      end
    end
  end
end
