use_frameworks!

def shared_pods
  pod 'RxAlamoRecord', :path => '../'
end

target 'RxAlamoRecord_Example' do
  shared_pods
  pod 'SnapKit'
  pod 'NotificationBannerSwift'
  pod 'KeyboardSpy'
end

target 'RxAlamoRecordTests' do
  shared_pods
end
